version: "3.8"

services:
  app-frontend:
    container_name: app-frontend
    build: app_frontend
    restart: always
    tty: true
    ports:
      - 8001:8001
    logging:
      options:
        max-size: "100m"
        max-file: "100"
    env_file:
      - ./.env_web_app
