version: "3.8"

services:
  app-board:
    container_name: app-board
    build: app_board
    restart: always
    tty: true
    ports:
      - 8051:80
    logging:
      options:
        max-size: "100m"
        max-file: "100"
    env_file:
      - ./.env_web_board
    networks:
      - web

networks:
  web:
    external: true #needs to be created by other file
    name: shared-web
