version: "3.8"

services:
  app-board:
    container_name: app-board
    build: app_board
    restart: always
    tty: true
    ports:
      - 8002:80
    logging:
      options:
        max-size: "100m"
        max-file: "100"
    env_file:
      - ./.env_web_board
